// Generated by Chudbot before every Vibe build. Local edits are overwritten.
type VibeJsonPrimitive = string | number | boolean | null;
type VibeJsonValue =
  | VibeJsonPrimitive
  | VibeJsonValue[]
  | { [key: string]: VibeJsonValue };

type VibeIdentity = {
  id: string;
  username: string;
  displayName: string;
  avatarUrl: string | null;
  guild: { id: string; displayName: string };
  site: { name: string };
};

type VibeRoomUser = {
  id: string;
  username?: string;
  displayName: string;
  avatarUrl: string | null;
  anonymous: boolean;
  states: Readonly<Record<string, VibeJsonValue>>;
};

type VibeRoomEventHandler = (event: VibeJsonValue, user: VibeRoomUser) => void;
type VibeRoomUserHandler = (user: VibeRoomUser) => void;
type VibeRoomStateHandler = (
  user: VibeRoomUser,
  before: VibeJsonValue | undefined,
  after: VibeJsonValue,
) => void;

interface VibeRoomConnection {
  readonly self: VibeRoomUser;
  readonly users: readonly VibeRoomUser[];
  broadcast(event: unknown, label: string): Promise<void>;
  setUserState(key: string, value: unknown): Promise<void>;
  disconnect(): Promise<void>;
}

interface VibeRoom {
  readonly name: string;
  on(event: "user:join" | "user:quit", handler: VibeRoomUserHandler): () => void;
  on(label: string, handler: VibeRoomEventHandler): () => void;
  onUserState(key: string, handler: VibeRoomStateHandler): () => void;
  join(): Promise<VibeRoomConnection>;
}

declare const vibe: {
  readonly version: "1";
  identity(): Promise<VibeIdentity | null>;
  room(name: string): VibeRoom;
};
