//! `generate_image` client tool.

use super::*;

const MAX_REFERENCE_IMAGES: usize = 3;

/// Image generation tool that stores generated bytes and returns a media URI.
#[derive(Debug)]
pub(crate) struct ImageGeneratorTool<G, M> {
    generator: G,
    media_store: M,
    description: String,
}

impl<G, M> ImageGeneratorTool<G, M> {
    pub(crate) fn new(generator: G, media_store: M) -> Self {
        Self {
            generator,
            media_store,
            description: concat!(
                "Generate an image, edit/restyle/combine existing images when reference URIs ",
                "are available, save it to media storage, and return its media URI."
            )
            .to_string(),
        }
    }

    pub(crate) fn with_description(mut self, description: impl Into<String>) -> Self {
        self.description = description.into();
        self
    }
}

impl<G, M> ImageGeneratorTool<G, M>
where
    G: ImageGenerator,
    M: MediaStore,
{
    pub(crate) fn spec(&self) -> ClientToolSpec {
        ClientToolSpec {
            description: self.description.clone(),
            input_schema: image_tool_schema(),
        }
    }

    #[tracing::instrument(
        name = "tool.generate_image",
        skip_all,
        fields(tool = %call.name, tool_call = %call.id)
    )]
    pub(crate) async fn call(
        &self,
        call: ClientToolCall,
    ) -> Result<ClientToolOutput, BotToolError> {
        let request = image_request_from_tool_input(&self.media_store, call.input).await?;
        tracing::debug!(
            prompt_chars = request.prompt.chars().count(),
            references = request.references.len(),
            aspect_ratio = ?request.aspect_ratio.as_deref(),
            model = ?request.model.as_ref().map(ModelId::as_str),
            "parsed image tool request"
        );

        let GeneratedImage {
            bytes,
            mime_type,
            model,
            revised_prompt,
            usage,
        } = self
            .generator
            .generate_image(request)
            .await
            .map_err(|error| BotToolError::Generator(error.to_string()))?;
        tracing::info!(
            model = %model,
            mime_type = %mime_type,
            bytes = bytes.len(),
            revised_prompt = revised_prompt.is_some(),
            usage_records = usage.len(),
            "image generated"
        );

        let media = self
            .media_store
            .create_media(CreateMedia {
                category: MediaCategory::Image,
                bytes,
                mime_type: Some(mime_type),
                name: None,
                extension: None,
            })
            .await
            .map_err(|error| BotToolError::Media(error.to_string()))?;
        let public_url = media.public_url().await.ok();
        let extra = serde_json::json!({
            "model": model.as_str(),
            "revised_prompt": revised_prompt,
        });
        let trace_response = image_media_trace_json(
            media.as_ref(),
            public_url.as_ref().map(|url| url.as_str()),
            extra.clone(),
        );
        let result = image_media_model_result_json(media.as_ref(), extra);
        tracing::info!(
            uri = %media.uri(),
            name = media.name(),
            bytes = media.size_bytes(),
            has_public_url = public_url.is_some(),
            "image tool completed"
        );

        Ok(ClientToolOutput {
            result: ClientToolResultContent::Json {
                value: result.clone(),
            },
            media: Vec::new(),
            is_error: false,
            trace_response,
            usage,
        })
    }
}

pub(crate) async fn image_request_from_tool_input<M>(
    media_store: &M,
    input: serde_json::Value,
) -> Result<ImageRequest, BotToolError>
where
    M: MediaStore,
{
    let prompt = tool_required_string(&input, "prompt")?;
    let mut references = Vec::new();
    if let Some(value) = input
        .get("reference_images")
        .or_else(|| input.get("references"))
    {
        let values = value.as_array().ok_or_else(|| {
            BotToolError::InvalidInput("`reference_images` must be an array".to_string())
        })?;
        if values.len() > MAX_REFERENCE_IMAGES {
            return Err(BotToolError::InvalidInput(format!(
                "`reference_images` must contain at most {MAX_REFERENCE_IMAGES} items"
            )));
        }
        for value in values {
            references
                .push(resolve_tool_media_arg(media_store, MediaCategory::Image, value).await?);
        }
    }

    Ok(ImageRequest {
        prompt,
        references,
        aspect_ratio: tool_optional_string(&input, "aspect_ratio")?,
        model: tool_optional_string(&input, "model")?.map(ModelId::new),
    })
}

fn image_media_trace_json(
    media: &dyn MediaRef,
    public_url: Option<&str>,
    extra: serde_json::Value,
) -> serde_json::Value {
    serde_json::json!({
        "uri": media.uri().as_str(),
        "category": media.category(),
        "name": media.name(),
        "mime_type": media.mime_type(),
        "size_bytes": media.size_bytes(),
        "public_url": public_url,
        "extra": extra,
    })
}

fn image_media_model_result_json(
    media: &dyn MediaRef,
    extra: serde_json::Value,
) -> serde_json::Value {
    serde_json::json!({
        "uri": media.uri().as_str(),
        "category": media.category(),
        "mime_type": media.mime_type(),
        "size_bytes": media.size_bytes(),
        "delivery": {
            "platform_reply": "The generated media will be attached to the final platform reply automatically. Do not paste media URIs, filenames, public URLs, or markdown image/video links in user-facing text."
        },
        "extra": extra,
    })
}

pub(crate) fn image_tool_schema() -> ToolInputSchema {
    let prompt_description = concat!(
        "Detailed description of the image to generate or the full desired result when editing ",
        "a reference image."
    );
    let reference_images_description = concat!(
        "Optional list of 1-3 existing images to edit, restyle, transform, vary, or combine. ",
        "Prefer this when the user refers to an image already visible in the conversation, ",
        "such as \"this image\", \"the image above\", or \"make it...\". Use exact ",
        "file://images/... URIs from prior tool results, generated-media notes, or image ",
        "attachment reference notes; public https URLs also work. Never invent paths. For ",
        "2-3 references, refer to them in the prompt as <IMAGE_0>, <IMAGE_1>, etc. in this ",
        "array's order."
    );
    ToolInputSchema::new(serde_json::json!({
        "type": "object",
        "required": ["prompt"],
        "properties": {
            "prompt": {
                "type": "string",
                "description": prompt_description
            },
            "reference_images": {
                "type": "array",
                "description": reference_images_description,
                "maxItems": MAX_REFERENCE_IMAGES,
                "items": { "type": "string" }
            },
            "aspect_ratio": {
                "type": "string",
                "description": "Optional provider-specific aspect ratio."
            },
            "model": {
                "type": "string",
                "description": "Optional provider-specific model id or quality tier."
            }
        },
        "additionalProperties": false
    }))
}
